# This an autogenerated file
# 
# Generated with ComparisonGroups
from dmt.entity import Entity
from dmt.blueprint import Blueprint
from .blueprints.comparisongroups import ComparisonGroupsBlueprint
from typing import Dict,Sequence,List
from ForApp.io.parametervariations import ParameterVariations

class ComparisonGroups(Entity):
    """
    
    
    Keyword arguments
    -----------------
    name : str 
         (default "")
    description : str 
         (default "")
    parameterVariations : List[ParameterVariations] 
         
    """

    def __init__(self , name:str="", description:str="",
        parameterVariations:list[ParameterVariations]=None, **kwargs):
        self.__name = name
        self.__description = description
        self.__parameterVariations = list() if parameterVariations is None else parameterVariations
        for key, value in kwargs.items():
            if not isinstance(value, Dict):
                setattr(self, key, value)


    @property
    def blueprint(self) -> Blueprint:
        """Return blueprint that this entity represents"""
        return ComparisonGroupsBlueprint()


    @property
    def name(self) -> str:
        """"""
        return self.__name

    @name.setter
    def name(self, value: str):
        """Set name"""
        self.__name = str(value)

    @property
    def description(self) -> str:
        """"""
        return self.__description

    @description.setter
    def description(self, value: str):
        """Set description"""
        self.__description = str(value)

    @property
    def parameterVariations(self) -> List[ParameterVariations]:
        """"""
        return self.__parameterVariations

    @parameterVariations.setter
    def parameterVariations(self, value: List[ParameterVariations]):
        """Set parameterVariations"""
        if not isinstance(value, Sequence):
            raise Exception("Expected sequense, but was " , type(value))
        self.__parameterVariations = value
